export const HOME_FETCH_TOPICS_BEGIN = 'HOME_FETCH_TOPICS_BEGIN';
export const HOME_FETCH_TOPICS_SUCCESS = 'HOME_FETCH_TOPICS_SUCCESS';
export const HOME_FETCH_TOPICS_FAILURE = 'HOME_FETCH_TOPICS_FAILURE';
export const HOME_FETCH_TOPICS_DISMISS_ERROR = 'HOME_FETCH_TOPICS_DISMISS_ERROR';
